name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ACTIONS_STEP_DEBUG: true  # Ativa logs de debug

jobs:
  validate:
    name: Validação de Sintaxe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar sintaxe do script
        run: |
          if ! bash -n status-check.sh; then
            echo "::error::Erro de sintaxe no script status-check.sh"
            exit 1
          else
            echo "::warning::Script verificado, mas recomenda-se testes mais robustos."
          fi

  test:
    name: Simulação de Testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        run: |
          echo "Running tests"
          echo "::warning::Nenhum teste real foi executado - apenas simulação."
          exit 0

  package:
    name: Empacotamento e Summary
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar artefato report.zip
        run: zip -r report.zip .

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Gerar resumo do job
        run: |
          echo "### CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Ambiente: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ✅ Todos os steps executados com sucesso" >> $GITHUB_STEP_SUMMARY
          echo "- Artefato: [Download report.zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
