name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar sintaxe do script
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        run: |
          echo "Running tests"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar artefato report.zip
        run: zip -r report.zip .

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
