name: Deploy para produção

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    name: Job de Deploy (após aprovação)
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://appmonitor.com
    steps:
      - name: Simular deploy para o domínio de produção
        run: echo "Deploying to ${{ vars.PROD_DOMAIN }}"
