name: Demonstrar variáveis, secrets e contextos

on:
  workflow_dispatch:

jobs:
  ambiente:
    name: Job 1 - Usando env com vars
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV }}
    steps:
      - name: Exibir ambiente de execução
        run: |
          echo "Ambiente: $APP_ENV"

  variaveis:
    name: Job 2 - Usando context.vars diretamente
    runs-on: ubuntu-latest
    steps:
      - name: Exibir e-mail de suporte
        run: |
          echo "Contato: ${{ vars.SUPPORT_EMAIL }}"

  segredo:
    name: Job 3 - Usando context.secrets com env
    runs-on: ubuntu-latest
    steps:
      - name: Simular uso da chave de API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Chave de API recebida e disponível em ambiente"

